-- ============================================================
-- Migration v34 — intégrité des séances + bilans + relances
--
-- À exécuter dans Supabase → SQL Editor. Idempotente : elle peut être
-- relancée sans risque. Le code fonctionne AVANT et APRÈS son application
-- (replis explicites), mais tant qu'elle n'est pas passée :
--   • history.session_id / history.rpe ne sont pas écrits ;
--   • les bilans de séance restent dans programs.data (purgés à 84 j) ;
--   • les relances push ne sont pas dédoublonnées (jusqu'à 1 push/jour).
-- ============================================================

-- ── 1. Identité de séance et RPE en colonnes ──────────────────
-- Une séance = (user_id, date, seance). session_id est calculé côté Flask
-- (uuid5 déterministe) et partagé par toutes les séries d'une même séance :
-- il permet de compter, dater et supprimer une séance sans deviner.
alter table public.history
  add column if not exists session_id uuid,
  add column if not exists rpe numeric(3,1);

comment on column public.history.session_id is
  'Identifiant de la séance (uuid5 de user|date|seance). Partagé par les séries.';
comment on column public.history.rpe is
  'Effort ressenti 6..10. Remplace le token « @RPE8 » encodé dans remarque.';

-- Renseigne les lignes existantes : un id par (user, date, séance).
update public.history
   set session_id = md5(user_id::text || '|' || coalesce(date::text, '') || '|' || coalesce(seance, ''))::uuid
 where session_id is null
   and date is not null;

-- Récupère les RPE déjà stockés dans la remarque (« @RPE8 », « @RPE8.5 »).
update public.history
   set rpe = nullif(substring(remarque from '@RPE([0-9]+(?:\.5)?)'), '')::numeric
 where rpe is null
   and remarque ~ '@RPE[0-9]';

-- ── 2. Index de lecture ───────────────────────────────────────
-- Le chemin chaud est « toutes les séries d'un user, par date » (affichage
-- séance, accueil, progrès) puis le ciblage exact (user, date, séance, exo)
-- utilisé par chaque enregistrement.
create index if not exists history_user_date_idx
  on public.history (user_id, date desc);

create index if not exists history_user_date_seance_exo_idx
  on public.history (user_id, date, seance, exercice);

create index if not exists history_session_idx
  on public.history (session_id)
  where session_id is not null;

-- ── 3. Bilans de séance dans leur propre table ────────────────
-- Ils vivaient dans programs.data['_session_notes'], donc : effacés par
-- certaines sauvegardes du programme, et purgés au bout de 84 jours. Ce sont
-- des données utilisateur : elles méritent une table et aucune expiration.
create table if not exists public.session_notes (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users (id) on delete cascade,
  date        date not null,
  seance      text not null default '',
  rating      smallint check (rating between 1 and 5),
  comment     text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (user_id, date, seance)
);

create index if not exists session_notes_user_date_idx
  on public.session_notes (user_id, date desc);

alter table public.session_notes enable row level security;

-- Le backend Flask accède en service_role (bypass RLS) et filtre lui-même par
-- user_id ; aucune policy publique n'est nécessaire. RLS activée = la clé anon
-- ne peut rien lire même si elle fuitait.

-- ── 4. Dédoublonnage des relances push ────────────────────────
alter table public.push_subscriptions
  add column if not exists last_reactivation_at timestamptz,
  add column if not exists reactivation_count   smallint not null default 0;

comment on column public.push_subscriptions.reactivation_count is
  'Nombre de relances déjà envoyées (plafonné à 3 côté applicatif).';

-- ── 5. Vue « dernière activité » pour le ciblage des relances ──
-- Remplace la lecture intégrale de history par le cron (qui, au-delà de
-- 1 000 lignes, ciblait faux à cause du plafond PostgREST).
create or replace view public.user_last_activity as
  select user_id, max(date) as last_date
    from public.history
   where (reps > 0 or poids > 0)
     and exercice <> 'SESSION'
   group by user_id;

-- Les vues héritent des droits de l'appelant ; service_role y accède.
grant select on public.user_last_activity to service_role;
